version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  postgresql:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=PYMS
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    volumes:
      - sqlserver-data:/var/opt/mssql
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Password01"
      ACCEPT_EULA: "Y"
volumes:
  postgres-data:
    external: false
  sqlserver-data:
    external: false
